# 4. NUMPY Y PANDAS SERIES

**EJERCICIOS:**

Antes de empezar a resolver ejercicios con Numpy y Pandas, aprendamos a importar una librería en Python.

Una librería está compuesta por un conjunto de funciones que podremos usar una vez la hemos importado. Para importar cualquier libreria en Python debemos usar el comando import, pero hay dos buenas prácticas para importarlas.

1. La manera más común: **importar la librería entera y renombrarla si nos interesa** mediante la palabra 'as'. Por ejemplo numpy suele ser renombrado como np.

In [1]:
import numpy as np

Con esta primera forma, cada vez que llamemos a una función de la librería deberemos poner el nombre de la librería seguido de un punto antes de la función, o en su defecto, si la hemos renombrado deberemos poner el nombre que le hemos asignado. Veamos un ejemplo a continuación:

In [2]:
arr = np.array([1,2,2])

In [3]:
arr = array([1,2,2])

NameError: name 'array' is not defined

Como podéis ver, si no ponemos la librería de la que procede la función nos da error.

2. La segunda forma es muy usada cuando **solo queremos alguna función en concreto de una libreria** y no necesitamos importar toda la librería entera. Por ejemplo, si solo quisieramos la función array de numpy haríamos lo siguiente:

Si llevamos a cabo este procedimiento, al usar las funciones concretas que importemos no hará falta indicar la librería de la que proceden como en el punto anterior. Veámoslo a continuación:

In [4]:
from numpy import array

In [5]:
arr = array([8,9,1])

Ahora no nos ha dado ningún error.

Empecemos con los ejercicios:


**Ejercicio 1**
Importa la libreria numpy y renombrala como np

In [6]:
import numpy as np

**Ejercicio 2** Crea un array a partir de la lista [1,2,3] y comprueba el tipo de variable que has creado mediante la función dtype como hicimos en los ejercicios de la primera unidad

In [7]:
arr = array( [1,2,3])

In [8]:
type(arr)

numpy.ndarray

**Ejercicio 3** Crea un array a partir de la lista definida a continuación 

In [9]:
#Definimos la lista
lista1 = [3,6,2,1]

In [10]:
#Crea el array a partir de lista1
array(lista1)

array([3, 6, 2, 1])

**Ejercicio 4** Crea un array de dos dimensiones, es decir, crea un array a partir de una lista que contenga listas. Un array de dos dimensiones también se llama una **matriz**

In [11]:
arr2d = array([[1,2,3],[1,2,3]])

In [12]:
arr2d

array([[1, 2, 3],
       [1, 2, 3]])

**Ejercicio 5** Completa el código substituyendo los guiones bajos con la función necesaria para crear un array de medida 6 lleno de **ceros**

In [13]:
arr1 = np.zeros(6)
print(arr1)

[0. 0. 0. 0. 0. 0.]


**Ejercicio 6** Completa el código substituyendo los guiones bajos con la función necesaria para crear un array de medida 6 lleno de **unos**

In [14]:
arr2 = np.empty(6)
print(arr2)

[0. 0. 0. 0. 0. 0.]


**Ejercicio 7** Crea un array vacío de medida 10 mediante la función empty

In [15]:
arr3 = np.empty(10)
print(arr3)

[nan  0.  0.  0.  0.  0.  0.  0.  0.  0.]


**Ejercicio 8** Crea un array que contenga los múltiples de 5 del 0 al 25 (es decir: 0,5,10,...,25) mediante la función arange

In [16]:
arr3 = np.array(range(0,26,5))

In [17]:
arr3

array([ 0,  5, 10, 15, 20, 25])

**Ejercicio 9** Escribe la medida que crees que tiene el array arr3 y luego comprueba si has acertado con la función np.size()

In [18]:
#definimos el array arr3 4 
arr3 = np.array([4,7,8, 5])

In [19]:
#comprueba su medida
np.size(arr3)

4

**Ejercicio 10** Ahora escribe las dimensiones (forma) que crees que tiene arr3 y luego compruebalo con la función np.shape()

In [20]:
# una dimension
np.shape(arr3)

(4,)

**Ejercicio 11** Substituye la almohadilla # y obtén el primer elemento de arr3, definido en el ejercicio 9, y guardalo en la variable first_item:

In [21]:
first_item = arr3[0]

In [22]:
print(first_item)

4


Ahora substituye la almohadilla # y obtén el último elemento de arr3 guardado en last_item. Recuerda que puedes usar también números negativos:

In [23]:
last_item = arr3[-1]

In [24]:
print(last_item)

5


**Ejercicio 12** Haz lo mismo que en los ejercicios 9, 10 y 11 pero para arr4

In [25]:
arr4 = np.array([[2,6,4], [1,3,8]])

In [26]:
np.size(arr4)

6

In [27]:
first_item = arr4[0]
print(first_item)

[2 6 4]


In [28]:
last_item = arr4[-1]
print(last_item)

[1 3 8]


**Ejercicio 13** Substituye las almohadillas # por los número correspondientes para que arr4_item = 6, teniendo en cuenta que arr4 es el array definido en el ejercicio anterior


In [29]:
#forma 1
arr4_item = arr4[0][1]
print(arr4_item)

6


In [30]:
#forma 2
arr4_item = arr4[0,1]
print(arr4_item)

6


**Ejercicio 14** Substituye la almohadilla para que new_arr4 = [1,3,8]

In [31]:
new_arr4 = arr4[1]
print(new_arr4)

[1 3 8]


**Ejercicio 15** Define un array llamado my_array de manera que my_slice = my_array[2][3] sea igual a 2 y my_second_slice = my_array[0][1] sea igual a 4. Comprueba que lo haas hecho bien ejecutando la segunda celda.

In [32]:
#Define my_array
my_array = [[0,4,0,0],[0,0,0,0],[0,0,0,2]]

In [33]:
my_slice = my_array[2][3]
print(my_slice)

2


In [34]:
my_second_slice = my_array[0][1]
print(my_second_slice)

4


In [35]:
#Comprobamos que my_array esté definido correctamente (solo ejecutar)

my_slice = my_array[2][3]
my_second_slice = my_array[0][1]

if my_slice!=2 or my_second_slice!=4:
  print('Error! O bien my_slice o bien my_second_slice no corresponden a los resultados indicados')
else:
  print('Correcto! my_slice y my_second_slice contienen los resultados esperados')

Correcto! my_slice y my_second_slice contienen los resultados esperados


**Ejercicio 16** Substituye los guiones bajos de manera que en w1 tengamos todos los elementos menores o iguales que 5 de v1. Imprime w1 para comprobarlo.

In [36]:
v1 = np.array([2,7,1,8,9,5,4])

In [37]:
w1 = v1[(v1<=5)]
print(w1)

[2 1 5 4]


Ahora haz que w2 contenga todos los elementos mayores que 5 de v1 y el número 2 de v1. Imprime w2 para comprobarlo.

In [38]:
w2 = v1[(v1>5) | (v1==2)]
print(w2)

[2 7 8 9]


**Ejercicio 17** Multiplica w1 por 2 y sumale w2 al resultado, guárdalo en w3 e imprímelo.

In [39]:
w3 = (w1*2)+w2
print(w3)

[ 6  9 18 17]


**Ejercicio 18** Concatena los arrays w1 y w2 con la función np.concatenate() e imprime el resultado

In [40]:
np.concatenate((w1,w2))

array([2, 1, 5, 4, 2, 7, 8, 9])

**Ejercicio 19** Sean a y b los arrays definidos a continuación, piensa en que resultados crees que tendrán las operaciones siguientes. Luego programalas, ejecuta y comprueba si has acertado el resultado

* a-b*2
* (a+b)/3
* b**2
* a%2


In [41]:
#Definimos los arrays a y b
a = np.array([2,1,1,5,4])
b = np.array([0,7,0,4,6])

In [42]:
a-b*2

array([  2, -13,   1,  -3,  -8])

In [43]:
(a+b)/3

array([0.66666667, 2.66666667, 0.33333333, 3.        , 3.33333333])

In [44]:
b**2

array([ 0, 49,  0, 16, 36])

In [45]:
a%2

array([0, 1, 1, 1, 0], dtype=int32)

**Ejercicio 20** Crea una array con las alturas de los 10 alumnos de una clase, luego calcula la media y la mediana de las alturas de los alumnos con las funciones np.mean() y np.median()

In [46]:
alumnos = np.array([1.60,1.75,1.65,1.85])

In [47]:
np.mean(alumnos) 

1.7125

In [48]:
np.median(alumnos)

1.7

**Ejercicio 21** Ha llegado una chica nueva a la clase, añade su altura en el array del ejercicio anterior mediante la función np.append() y luego ordena las alturas de menor a mayor con la función np.sort(). Piensa también una manera de ordenar las alturas de mayor a menor.

In [49]:
alumnos = np.append(alumnos,1.62)

In [50]:
alumnos = np.sort(alumnos)

**Ejercicio 22** Importa la librería Pandas y crea una serie de Pandas a partir del array del ejercicio anterior

In [51]:
import pandas as pd

In [52]:
pd.Series(alumnos)

0    1.60
1    1.62
2    1.65
3    1.75
4    1.85
dtype: float64

**Ejercicio 23** Guarda en un nuevo array las 3 últimas alturas del ejercicio 21, las de los alumnos más altos. Luego crea una Serie con estas tres alturas y define como index de la Serie los nombres de los alumnos asociados (invéntatelos)

In [53]:
alumnos_last = alumnos[-3:]

In [54]:
alumnos_last

array([1.65, 1.75, 1.85])

In [55]:
alumnos_lastd = pd.Series(alumnos_last,index=["ana","pedro",'juan'])

**Ejercicio 24** Selecciona el alumno más alto de la serie del ejercicio anterior. Puedes hacerlo usando los corchetes [ ], o también recuerda que en Pandas Series tenemos las funciones head() y tail()

In [56]:
alumnos_lastd.tail(1)

juan    1.85
dtype: float64

**Ejercicio 25** Definimos el diccionario dict1 formado por los nombres de 5 personas junto con sus edades. Crea una serie de Pandas a partir de este diccionario, definiendo el nombre como index y la edad como values.

In [57]:
dict1 = {"Juliana":18,
        "Marta": 17,
        alumnos_lastd.index[0] : 17,
        alumnos_lastd.index[1] : 16,
        alumnos_lastd.index[2] : 19}

In [58]:
dict1

{'Juliana': 18, 'Marta': 17, 'ana': 17, 'pedro': 16, 'juan': 19}

**Ejercicio 26** Selecciona la edad de Marta a partir del labeled index de la serie creada en el ejercicio anterior 

In [59]:
dict1s = pd.Series(dict1)

In [60]:
dict1s["Marta"]

17

**Ejercicio 27** Selecciona la edad de la persona más mayor de dict1. Recuerda que podemos usar las funciones max() o nlargest()

In [61]:
dict1s.max()

19

**Ejercicio 28** Calcula la media de las edades de la serie elaborada a partir de dict1 mediante la función mean()

In [62]:
dict1s.mean()

17.4